version: "3"
services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
    environment:
      MYSQL_AUTO_CREATE_ACCOUNTS: true

volumes:
  postgres:
    driver: local
